name: Export files

on:
  [push]

jobs:
  build:
    strategy:
      matrix:
        tooth: [
          36,
          10,
          60
        ]
        missing: [1,2]
        exclude:
          - tooth: 36
            missing: 2
          - tooth: 10
            missing: 2
          - tooth: 60
            missing: 1
      # fast-fail: false
    
    uses: ./.github/workflows/dxf_wf.yml
    with:
      tooth: ${{ matrix.tooth }}
      missing: ${{ matrix.missing }}
      tooth_length: 10
      tooth_duty_cycle: 50
      tooth_radius: 1
      diameter: 180
      thickness: 5
      hole_diameter: 14
      slit_width: 10
      slit_depth: 40
      slit_count: 10
      slit_offset: 50